import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--epoch', type=int, default=300, help='epoch number')
parser.add_argument('--lr', type=float, default=5e-5, help='learning rate')
parser.add_argument('--batchsize', type=int, default=8, help='training batch size')
parser.add_argument("--num_workers", type=int, default=8)
parser.add_argument('--trainsize', type=int, default=384, help='training dataset size')
parser.add_argument('--clip', type=float, default=0.5, help='gradient clipping margin')
parser.add_argument('--decay_rate', type=float, default=0.1, help='decay rate of learning rate')
parser.add_argument('--decay_epoch', type=int, default=100, help='every n epochs decay learning rate')
parser.add_argument('--load', type=str, default="./swin_base_patch4_window12_384.pth", help='train from checkpoints')
parser.add_argument('--load_pre', type=str, default='./swin_base_patch4_window12_384.pth', help='train from checkpoints')
parser.add_argument('--gpu_id', type=str, default='0', help='train use gpu')
parser.add_argument("--data_path", type=str, default='C:/datasets/SOD-T/')
#parser.add_argument("--backbonet_path", type=str, default="/swin_base_patch4_window12_384.pth")
parser.add_argument('--mean', default=(0.485, 0.456, 0.406))
parser.add_argument('--std', default=(0.229, 0.224, 0.225))
parser.add_argument('--save_path', type=str, default="./ckpts/", help='the path to save models and logs')
opt = parser.parse_args()